-- Production cutover cleanup for dealer test data.
-- Preserves HQ members/applications, global products/categories, and HQ notices.

START TRANSACTION;

CREATE TEMPORARY TABLE TMP_DEALER_MALL_IDS (ID BIGINT PRIMARY KEY);
INSERT INTO TMP_DEALER_MALL_IDS (ID)
SELECT ID FROM HEALTH_BOX_DEALER_MALL;

CREATE TEMPORARY TABLE TMP_DEALER_MEMBER_IDS (ID BIGINT PRIMARY KEY);
INSERT INTO TMP_DEALER_MEMBER_IDS (ID)
SELECT ID FROM HEALTH_BOX_BUYER_MEMBER
WHERE DEALER_MALL_ID IN (SELECT ID FROM TMP_DEALER_MALL_IDS);

CREATE TEMPORARY TABLE TMP_DEALER_ACCOUNT_IDS (ID BIGINT PRIMARY KEY);
INSERT IGNORE INTO TMP_DEALER_ACCOUNT_IDS (ID)
SELECT ACCOUNT_ID FROM HEALTH_BOX_BUYER_MEMBER
WHERE ID IN (SELECT ID FROM TMP_DEALER_MEMBER_IDS) AND ACCOUNT_ID IS NOT NULL;
INSERT IGNORE INTO TMP_DEALER_ACCOUNT_IDS (ID)
SELECT ACCOUNT_ID FROM HEALTH_BOX_ACCOUNT_ROLE
WHERE DEALER_MALL_ID IN (SELECT ID FROM TMP_DEALER_MALL_IDS);

CREATE TEMPORARY TABLE TMP_DEALER_ORDER_IDS (ID BIGINT PRIMARY KEY);
INSERT INTO TMP_DEALER_ORDER_IDS (ID)
SELECT ID FROM HEALTH_BOX_ORDER_HEADER
WHERE DEALER_MALL_ID IN (SELECT ID FROM TMP_DEALER_MALL_IDS);

CREATE TEMPORARY TABLE TMP_DEALER_ORDER_ITEM_IDS (ID BIGINT PRIMARY KEY);
INSERT INTO TMP_DEALER_ORDER_ITEM_IDS (ID)
SELECT ID FROM HEALTH_BOX_ORDER_ITEM
WHERE ORDER_ID IN (SELECT ID FROM TMP_DEALER_ORDER_IDS);

CREATE TEMPORARY TABLE TMP_DEALER_SHIPMENT_IDS (ID BIGINT PRIMARY KEY);
INSERT INTO TMP_DEALER_SHIPMENT_IDS (ID)
SELECT ID FROM HEALTH_BOX_SHIPMENT
WHERE ORDER_ID IN (SELECT ID FROM TMP_DEALER_ORDER_IDS);

CREATE TEMPORARY TABLE TMP_DEALER_STAFF_IDS (ID BIGINT PRIMARY KEY);
INSERT INTO TMP_DEALER_STAFF_IDS (ID)
SELECT ID FROM HEALTH_BOX_ADMIN_STAFF
WHERE SCOPE_TYPE = 'DEALER'
   OR DEALER_MALL_ID IN (SELECT ID FROM TMP_DEALER_MALL_IDS);

DELETE FROM HEALTH_BOX_SHIPMENT_ITEM
WHERE SHIPMENT_ID IN (SELECT ID FROM TMP_DEALER_SHIPMENT_IDS)
   OR ORDER_ITEM_ID IN (SELECT ID FROM TMP_DEALER_ORDER_ITEM_IDS);
DELETE FROM HEALTH_BOX_SHIPMENT
WHERE ID IN (SELECT ID FROM TMP_DEALER_SHIPMENT_IDS);
DELETE FROM HEALTH_BOX_PAYMENT_CANCEL_REQUEST
WHERE ORDER_ID IN (SELECT ID FROM TMP_DEALER_ORDER_IDS);
DELETE FROM HEALTH_BOX_CLAIM
WHERE DEALER_MALL_ID IN (SELECT ID FROM TMP_DEALER_MALL_IDS)
   OR ORDER_ID IN (SELECT ID FROM TMP_DEALER_ORDER_IDS);
DELETE FROM HEALTH_BOX_PAYMENT
WHERE DEALER_MALL_ID IN (SELECT ID FROM TMP_DEALER_MALL_IDS)
   OR ORDER_ID IN (SELECT ID FROM TMP_DEALER_ORDER_IDS);
DELETE FROM HEALTH_BOX_ORDER_ITEM
WHERE ID IN (SELECT ID FROM TMP_DEALER_ORDER_ITEM_IDS);
DELETE FROM HEALTH_BOX_ORDER_HEADER
WHERE ID IN (SELECT ID FROM TMP_DEALER_ORDER_IDS);

DELETE FROM HEALTH_BOX_BUYER_ADDRESS
WHERE BUYER_MEMBER_ID IN (SELECT ID FROM TMP_DEALER_MEMBER_IDS);
DELETE FROM HEALTH_BOX_BUYER_CART_ITEM
WHERE DEALER_MALL_ID IN (SELECT ID FROM TMP_DEALER_MALL_IDS)
   OR BUYER_MEMBER_ID IN (SELECT ID FROM TMP_DEALER_MEMBER_IDS);
DELETE FROM HEALTH_BOX_PRODUCT_INQUIRY
WHERE DEALER_MALL_ID IN (SELECT ID FROM TMP_DEALER_MALL_IDS)
   OR BUYER_MEMBER_ID IN (SELECT ID FROM TMP_DEALER_MEMBER_IDS);
DELETE FROM HEALTH_BOX_BUYER_SIGNUP_APPLICATION
WHERE DEALER_MALL_ID IN (SELECT ID FROM TMP_DEALER_MALL_IDS);
DELETE FROM HEALTH_BOX_BUYER_MEMBER
WHERE ID IN (SELECT ID FROM TMP_DEALER_MEMBER_IDS);

DELETE FROM HEALTH_BOX_ACCOUNT_ROLE
WHERE DEALER_MALL_ID IN (SELECT ID FROM TMP_DEALER_MALL_IDS);
DELETE FROM HEALTH_BOX_ACCOUNT
WHERE ID IN (SELECT ID FROM TMP_DEALER_ACCOUNT_IDS)
  AND NOT EXISTS (
      SELECT 1 FROM HEALTH_BOX_BUYER_MEMBER member
      WHERE member.ACCOUNT_ID = HEALTH_BOX_ACCOUNT.ID
  )
  AND NOT EXISTS (
      SELECT 1 FROM HEALTH_BOX_ACCOUNT_ROLE role
      WHERE role.ACCOUNT_ID = HEALTH_BOX_ACCOUNT.ID
  );

DELETE FROM HEALTH_BOX_MONTHLY_SALES_SUMMARY
WHERE DEALER_MALL_ID IN (SELECT ID FROM TMP_DEALER_MALL_IDS);
DELETE FROM HEALTH_BOX_MONTHLY_SETTLEMENT_SUMMARY
WHERE DEALER_MALL_ID IN (SELECT ID FROM TMP_DEALER_MALL_IDS);
DELETE FROM HEALTH_BOX_NOTICE
WHERE DEALER_MALL_ID IN (SELECT ID FROM TMP_DEALER_MALL_IDS);
DELETE FROM HEALTH_BOX_DEALER_MALL_PUBLIC_CONFIG
WHERE DEALER_MALL_ID IN (SELECT ID FROM TMP_DEALER_MALL_IDS);

DELETE FROM HEALTH_BOX_ADMIN_STAFF_PERMISSION
WHERE STAFF_ID IN (SELECT ID FROM TMP_DEALER_STAFF_IDS);
DELETE FROM HEALTH_BOX_ADMIN_STAFF
WHERE ID IN (SELECT ID FROM TMP_DEALER_STAFF_IDS);

DELETE FROM HEALTH_BOX_DEALER_APPLICATION;
DELETE FROM HEALTH_BOX_DEALER_MALL
WHERE ID IN (SELECT ID FROM TMP_DEALER_MALL_IDS);

COMMIT;

ALTER TABLE HEALTH_BOX_DEALER_APPLICATION AUTO_INCREMENT = 1;
ALTER TABLE HEALTH_BOX_DEALER_MALL AUTO_INCREMENT = 1;
ALTER TABLE HEALTH_BOX_DEALER_MALL_PUBLIC_CONFIG AUTO_INCREMENT = 1;

SELECT 'dealer_malls_remaining' AS metric, COUNT(*) AS value FROM HEALTH_BOX_DEALER_MALL
UNION ALL SELECT 'dealer_applications_remaining', COUNT(*) FROM HEALTH_BOX_DEALER_APPLICATION
UNION ALL SELECT 'dealer_members_remaining', COUNT(*) FROM HEALTH_BOX_BUYER_MEMBER WHERE DEALER_MALL_ID <> 0
UNION ALL SELECT 'dealer_orders_remaining', COUNT(*) FROM HEALTH_BOX_ORDER_HEADER WHERE DEALER_MALL_ID <> 0
UNION ALL SELECT 'hq_members_preserved', COUNT(*) FROM HEALTH_BOX_BUYER_MEMBER WHERE DEALER_MALL_ID = 0
UNION ALL SELECT 'hq_applications_preserved', COUNT(*) FROM HEALTH_BOX_BUYER_SIGNUP_APPLICATION WHERE DEALER_MALL_ID = 0;
