-- Reset all test commerce data before production order intake.
-- Restores inventory still consumed by non-canceled order quantities and
-- removes order-derived sales/settlement summaries to keep admin totals aligned.

CREATE TABLE IF NOT EXISTS HEALTH_BOX_ORDER_DAILY_SEQUENCE (
    ORDER_DATE DATE NOT NULL,
    LAST_SEQUENCE INT NOT NULL,
    PRIMARY KEY (ORDER_DATE)
) ENGINE=InnoDB;

START TRANSACTION;

CREATE TEMPORARY TABLE TMP_ORDER_STOCK_RESTORE (
    SKU_ID BIGINT PRIMARY KEY,
    RESTORE_QUANTITY INT NOT NULL
);

INSERT INTO TMP_ORDER_STOCK_RESTORE (SKU_ID, RESTORE_QUANTITY)
SELECT
    SKU_ID,
    SUM(GREATEST(QUANTITY - CANCELED_QUANTITY, 0))
FROM HEALTH_BOX_ORDER_ITEM
GROUP BY SKU_ID;

UPDATE HEALTH_BOX_PRODUCT_SKU sku
JOIN TMP_ORDER_STOCK_RESTORE restore_stock ON restore_stock.SKU_ID = sku.ID
SET sku.STOCK_QUANTITY = COALESCE(sku.STOCK_QUANTITY, 0) + restore_stock.RESTORE_QUANTITY;

DELETE FROM HEALTH_BOX_SHIPMENT_ITEM;
DELETE FROM HEALTH_BOX_SHIPMENT;
DELETE FROM HEALTH_BOX_PAYMENT_CANCEL_REQUEST;
DELETE FROM HEALTH_BOX_CLAIM;
DELETE FROM HEALTH_BOX_PAYMENT;
DELETE FROM HEALTH_BOX_ORDER_ITEM;
DELETE FROM HEALTH_BOX_ORDER_HEADER;
DELETE FROM HEALTH_BOX_ORDER_DAILY_SEQUENCE;
DELETE FROM HEALTH_BOX_MONTHLY_SALES_SUMMARY;
DELETE FROM HEALTH_BOX_MONTHLY_SETTLEMENT_SUMMARY;

COMMIT;

ALTER TABLE HEALTH_BOX_SHIPMENT_ITEM AUTO_INCREMENT = 1;
ALTER TABLE HEALTH_BOX_SHIPMENT AUTO_INCREMENT = 1;
ALTER TABLE HEALTH_BOX_PAYMENT_CANCEL_REQUEST AUTO_INCREMENT = 1;
ALTER TABLE HEALTH_BOX_CLAIM AUTO_INCREMENT = 1;
ALTER TABLE HEALTH_BOX_PAYMENT AUTO_INCREMENT = 1;
ALTER TABLE HEALTH_BOX_ORDER_ITEM AUTO_INCREMENT = 1;
ALTER TABLE HEALTH_BOX_ORDER_HEADER AUTO_INCREMENT = 1;
ALTER TABLE HEALTH_BOX_MONTHLY_SALES_SUMMARY AUTO_INCREMENT = 1;
ALTER TABLE HEALTH_BOX_MONTHLY_SETTLEMENT_SUMMARY AUTO_INCREMENT = 1;

SELECT 'orders_remaining' AS metric, COUNT(1) AS value FROM HEALTH_BOX_ORDER_HEADER
UNION ALL SELECT 'order_items_remaining', COUNT(1) FROM HEALTH_BOX_ORDER_ITEM
UNION ALL SELECT 'payments_remaining', COUNT(1) FROM HEALTH_BOX_PAYMENT
UNION ALL SELECT 'shipments_remaining', COUNT(1) FROM HEALTH_BOX_SHIPMENT
UNION ALL SELECT 'shipment_items_remaining', COUNT(1) FROM HEALTH_BOX_SHIPMENT_ITEM
UNION ALL SELECT 'claims_remaining', COUNT(1) FROM HEALTH_BOX_CLAIM
UNION ALL SELECT 'payment_cancel_requests_remaining', COUNT(1) FROM HEALTH_BOX_PAYMENT_CANCEL_REQUEST
UNION ALL SELECT 'daily_sequences_remaining', COUNT(1) FROM HEALTH_BOX_ORDER_DAILY_SEQUENCE
UNION ALL SELECT 'sales_summaries_remaining', COUNT(1) FROM HEALTH_BOX_MONTHLY_SALES_SUMMARY
UNION ALL SELECT 'settlement_summaries_remaining', COUNT(1) FROM HEALTH_BOX_MONTHLY_SETTLEMENT_SUMMARY;
