-- Health-box buyer consent migration. Additive only: no existing member or application data is removed.
ALTER TABLE HEALTH_BOX_BUYER_SIGNUP_APPLICATION
    ADD COLUMN BIRTH_DATE date NULL;
ALTER TABLE HEALTH_BOX_BUYER_SIGNUP_APPLICATION
    ADD COLUMN TERMS_AGREED_AT datetime(6) NULL;
ALTER TABLE HEALTH_BOX_BUYER_SIGNUP_APPLICATION
    ADD COLUMN PRIVACY_AGREED_AT datetime(6) NULL;
ALTER TABLE HEALTH_BOX_BUYER_SIGNUP_APPLICATION
    ADD COLUMN THIRD_PARTY_AGREED_AT datetime(6) NULL;
ALTER TABLE HEALTH_BOX_BUYER_SIGNUP_APPLICATION
    ADD COLUMN MARKETING_CONSENT_YN varchar(1) NOT NULL DEFAULT 'N';
ALTER TABLE HEALTH_BOX_BUYER_SIGNUP_APPLICATION
    ADD COLUMN MARKETING_CONSENT_UPDATED_AT datetime(6) NULL;
ALTER TABLE HEALTH_BOX_BUYER_SIGNUP_APPLICATION
    ADD COLUMN CONSENT_DOCUMENT_VERSION varchar(20) NULL;

ALTER TABLE HEALTH_BOX_BUYER_MEMBER
    ADD COLUMN BIRTH_DATE date NULL;
ALTER TABLE HEALTH_BOX_BUYER_MEMBER
    ADD COLUMN TERMS_AGREED_AT datetime(6) NULL;
ALTER TABLE HEALTH_BOX_BUYER_MEMBER
    ADD COLUMN PRIVACY_AGREED_AT datetime(6) NULL;
ALTER TABLE HEALTH_BOX_BUYER_MEMBER
    ADD COLUMN THIRD_PARTY_AGREED_AT datetime(6) NULL;
ALTER TABLE HEALTH_BOX_BUYER_MEMBER
    ADD COLUMN MARKETING_CONSENT_YN varchar(1) NOT NULL DEFAULT 'N';
ALTER TABLE HEALTH_BOX_BUYER_MEMBER
    ADD COLUMN MARKETING_CONSENT_UPDATED_AT datetime(6) NULL;
ALTER TABLE HEALTH_BOX_BUYER_MEMBER
    ADD COLUMN CONSENT_DOCUMENT_VERSION varchar(20) NULL;
