CREATE TABLE IF NOT EXISTS HEALTH_BOX_ADMIN_STAFF (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    SCOPE_TYPE VARCHAR(20) NOT NULL,
    DEALER_MALL_ID BIGINT NULL,
    ACCOUNT_ID BIGINT NULL,
    NAME VARCHAR(100) NOT NULL,
    LOGIN_ID VARCHAR(80) NOT NULL,
    PASSWORD_HASH VARCHAR(255) NOT NULL,
    PHONE VARCHAR(30) NOT NULL,
    EMAIL VARCHAR(150) NULL,
    POSITION_NAME VARCHAR(80) NULL,
    ROLE_TYPE VARCHAR(20) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    JOINED_AT DATETIME(6) NULL,
    LAST_LOGIN_AT DATETIME(6) NULL,
    MEMO VARCHAR(1000) NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_HEALTH_BOX_ADMIN_STAFF_LOGIN_ID (LOGIN_ID),
    KEY IDX_HEALTH_BOX_ADMIN_STAFF_SCOPE (SCOPE_TYPE, DEALER_MALL_ID),
    KEY IDX_HEALTH_BOX_ADMIN_STAFF_ACCOUNT (ACCOUNT_ID),
    KEY IDX_HEALTH_BOX_ADMIN_STAFF_STATUS (STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS HEALTH_BOX_ADMIN_STAFF_PERMISSION (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    STAFF_ID BIGINT NOT NULL,
    PERMISSION_CODE VARCHAR(80) NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE KEY UK_HEALTH_BOX_STAFF_PERMISSION (STAFF_ID, PERMISSION_CODE),
    KEY IDX_HEALTH_BOX_STAFF_PERMISSION_STAFF (STAFF_ID, STATUS)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS HEALTH_BOX_ADMIN_AUDIT_LOG (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    CREATED_AT DATETIME(6) NOT NULL,
    UPDATED_AT DATETIME(6) NOT NULL,
    ACTOR_STAFF_ID BIGINT NULL,
    ACTOR_NAME VARCHAR(120) NOT NULL,
    ACTOR_SCOPE VARCHAR(150) NULL,
    ACTION_CODE VARCHAR(80) NOT NULL,
    ACTION_LABEL VARCHAR(150) NOT NULL,
    TARGET_TYPE VARCHAR(80) NULL,
    TARGET_ID VARCHAR(100) NULL,
    TARGET_LABEL VARCHAR(255) NULL,
    DETAIL_TEXT VARCHAR(2000) NULL,
    REQUEST_METHOD VARCHAR(10) NOT NULL,
    REQUEST_PATH VARCHAR(500) NOT NULL,
    RESULT_STATUS VARCHAR(30) NOT NULL,
    PRIMARY KEY (ID),
    KEY IDX_HEALTH_BOX_ADMIN_AUDIT_CREATED (CREATED_AT),
    KEY IDX_HEALTH_BOX_ADMIN_AUDIT_ACTOR (ACTOR_STAFF_ID, CREATED_AT),
    KEY IDX_HEALTH_BOX_ADMIN_AUDIT_ACTION (ACTION_CODE, CREATED_AT)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
