ALTER TABLE HEALTH_BOX_NOTICE
    ADD COLUMN DEALER_MALL_ID BIGINT NULL AFTER ID;

CREATE INDEX IDX_HEALTH_BOX_NOTICE_SCOPE
    ON HEALTH_BOX_NOTICE (DEALER_MALL_ID, POST_STATUS, POSTED_AT);

ALTER TABLE HEALTH_BOX_DEALER_MALL_PUBLIC_CONFIG
    ADD COLUMN LOGO_URL VARCHAR(1000) NULL,
    ADD COLUMN FAVICON_URL VARCHAR(1000) NULL,
    ADD COLUMN MAIN_VISUAL_URL VARCHAR(1000) NULL,
    ADD COLUMN MIDDLE_BANNER_URL VARCHAR(1000) NULL,
    ADD COLUMN SHARE_THUMBNAIL_URL VARCHAR(1000) NULL,
    ADD COLUMN META_TITLE VARCHAR(255) NULL,
    ADD COLUMN META_DESCRIPTION VARCHAR(1000) NULL,
    ADD COLUMN MAIN_NAVIGATION_JSON LONGTEXT NULL,
    ADD COLUMN SEARCH_PLACEHOLDER VARCHAR(255) NULL,
    ADD COLUMN POLICY_TEXT LONGTEXT NULL,
    ADD COLUMN CUSTOMER_CENTER_TEXT LONGTEXT NULL;
