ALTER TABLE HEALTH_BOX_PUBLIC_SITE_CONFIG
    ADD COLUMN MAIN_VISUAL_LINK_URL VARCHAR(1000) NULL AFTER MAIN_VISUAL_URL,
    ADD COLUMN MIDDLE_BANNER_LINK_URL VARCHAR(1000) NULL AFTER MIDDLE_BANNER_URL;

ALTER TABLE HEALTH_BOX_DEALER_MALL_PUBLIC_CONFIG
    ADD COLUMN MAIN_VISUAL_LINK_URL VARCHAR(1000) NULL AFTER MAIN_VISUAL_URL,
    ADD COLUMN MIDDLE_BANNER_LINK_URL VARCHAR(1000) NULL AFTER MIDDLE_BANNER_URL;
