export const MAX_IMAGE_FILE_COUNT = 6;
export const MAX_IMAGE_FILE_SIZE = 4 * 1024 * 1024;
export const MAX_IMAGE_FILE_SIZE_MB = 4;
export const MAX_IMAGE_TOTAL_SIZE_MB = MAX_IMAGE_FILE_COUNT * MAX_IMAGE_FILE_SIZE_MB;
