-- 건강창고몰 주문 금액 명세 및 상품 문의 기능용 추가 마이그레이션
-- 운영 DB 백업 후 애플리케이션 배포 전에 1회 실행한다.

ALTER TABLE HEALTH_BOX_PUBLIC_SITE_CONFIG
    MODIFY COLUMN POLICY_TEXT LONGTEXT NULL;

ALTER TABLE HEALTH_BOX_PRODUCT
    MODIFY COLUMN SALES_POLICY_TEXT LONGTEXT NULL;

ALTER TABLE HEALTH_BOX_ORDER_HEADER
    ADD COLUMN IF NOT EXISTS PRODUCT_AMOUNT INT NOT NULL DEFAULT 0 AFTER DETAIL_ADDRESS,
    ADD COLUMN IF NOT EXISTS SHIPPING_FEE INT NOT NULL DEFAULT 0 AFTER PRODUCT_AMOUNT,
    ADD COLUMN IF NOT EXISTS DISCOUNT_AMOUNT INT NOT NULL DEFAULT 0 AFTER SHIPPING_FEE;

-- 기존 주문은 과거 총 결제금액 전체를 상품금액으로 보존한다.
UPDATE HEALTH_BOX_ORDER_HEADER
SET PRODUCT_AMOUNT = TOTAL_PAYMENT_AMOUNT
WHERE PRODUCT_AMOUNT = 0
  AND TOTAL_PAYMENT_AMOUNT > 0;

CREATE TABLE IF NOT EXISTS HEALTH_BOX_PRODUCT_INQUIRY (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    PRODUCT_ID BIGINT NOT NULL,
    BUYER_MEMBER_ID BIGINT NOT NULL,
    DEALER_MALL_ID BIGINT NOT NULL,
    QUESTION TEXT NOT NULL,
    PRIVATE_YN VARCHAR(1) NOT NULL DEFAULT 'N',
    STATUS VARCHAR(30) NOT NULL DEFAULT 'PENDING',
    ANSWER TEXT NULL,
    ANSWERED_AT DATETIME NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY (ID),
    INDEX IDX_HEALTH_BOX_INQUIRY_PRODUCT_ID (PRODUCT_ID, ID),
    INDEX IDX_HEALTH_BOX_INQUIRY_BUYER_ID (BUYER_MEMBER_ID, ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

-- 실결제 주문과 결제 취소 요청의 중복 처리를 방지한다.
-- 아래 조회 결과가 있으면 운영 데이터 확인 후 UNIQUE INDEX를 추가한다.
SELECT PAYMENT_KEY, COUNT(*) AS DUPLICATE_COUNT
FROM HEALTH_BOX_PAYMENT
WHERE PAYMENT_KEY IS NOT NULL
GROUP BY PAYMENT_KEY
HAVING COUNT(*) > 1;

SELECT PAYMENT_ORDER_ID, COUNT(*) AS DUPLICATE_COUNT
FROM HEALTH_BOX_PAYMENT
WHERE PAYMENT_ORDER_ID IS NOT NULL
GROUP BY PAYMENT_ORDER_ID
HAVING COUNT(*) > 1;

ALTER TABLE HEALTH_BOX_PAYMENT
    ADD UNIQUE INDEX UK_HEALTH_BOX_PAYMENT_KEY (PAYMENT_KEY),
    ADD UNIQUE INDEX UK_HEALTH_BOX_PAYMENT_ORDER_ID (PAYMENT_ORDER_ID);

CREATE TABLE IF NOT EXISTS HEALTH_BOX_PAYMENT_CANCEL_REQUEST (
    ID BIGINT NOT NULL AUTO_INCREMENT,
    REQUEST_ID VARCHAR(100) NOT NULL,
    ORDER_ID BIGINT NOT NULL,
    CANCEL_AMOUNT INT NOT NULL,
    STATUS VARCHAR(30) NOT NULL,
    CREATED_AT DATETIME NOT NULL,
    UPDATED_AT DATETIME NOT NULL,
    PRIMARY KEY (ID),
    UNIQUE INDEX UK_HEALTH_BOX_PAYMENT_CANCEL_REQUEST_ID (REQUEST_ID),
    INDEX IDX_HEALTH_BOX_PAYMENT_CANCEL_ORDER_ID (ORDER_ID, ID)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
